# Generated by Django 4.1.2 on 2022-10-18 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tienda_SM_App', '0002_remove_facturasventas_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Categoria de Prenda', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('numeroDocumento', models.CharField(blank=True, help_text='CUIT, CUIL ó DNI', max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre', max_length=20, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, default='', help_text='Calle y numero', max_length=40, verbose_name='Direccion')),
                ('localidad', models.CharField(blank=True, default='', max_length=20, verbose_name='Localidad')),
                ('provincia', models.CharField(blank=True, default='', max_length=20, verbose_name='Provincia')),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='FacturasVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de emisión')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de carga del pedido')),
                ('factura', models.IntegerField(blank=True, null=True, verbose_name='NumeroFactura')),
                ('remito', models.IntegerField(blank=True, null=True, verbose_name='NumeroRemito')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Producto', max_length=50)),
                ('talleN', models.IntegerField(help_text='Talle en numero', null=True)),
                ('talleL', models.CharField(blank=True, help_text='Talle en letra', max_length=4)),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('numeroDocumento', models.CharField(blank=True, help_text='CUIT, CUIL ó DNI', max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=40)),
                ('localidad', models.CharField(blank=True, max_length=30)),
                ('provincia', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=50)),
                ('telefono', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='fecha de emision', verbose_name='Fecha')),
                ('cliente', models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.clientes')),
                ('factura', models.ForeignKey(help_text='Factura', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.facturasventas')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosPedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, help_text='Fecha de carga del pedido')),
                ('pedido', models.ForeignKey(help_text='Pedido', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.pedidos')),
                ('producto', models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.productos')),
                ('proveedor', models.ForeignKey(help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.proveedores')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='idProducto',
            field=models.ForeignKey(help_text='Productos', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.productos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.proveedores'),
        ),
        migrations.CreateModel(
            name='PagoProveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha de pago', verbose_name='Fecha pago')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('importe', models.IntegerField(verbose_name='Importe')),
                ('factura', models.ForeignKey(help_text='Id de factura', on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.facturasventas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda_SM_App.productos')),
            ],
        ),
    ]
