# Generated by Django 4.1.2 on 2022-10-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_SM_App', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Formal'), (2, 'Deportivo')]),
        ),
    ]
