# Generated by Django 4.1.2 on 2022-11-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_SM_App', '0005_alter_productos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='talleL',
        ),
    ]
